name: markdownlint

on:
  pull_request:
    paths:
      - "**/*.md"
      - ".markdownlint.json"
      - ".github/workflows/markdownlint.yaml"
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: DavidAnson/markdownlint-cli2-action@eb5ca3ab411449c66620fe7f1b3c9e10547144b0 # v18
        with:
          globs: |
            README.md
            docs/**/*.md
